<?php

namespace Salt\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Salt\UserBundle\Entity\Organization;

/**
 * OrganizationRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class OrganizationRepository extends EntityRepository
{
    /**
     * Add a new organization to the system
     *
     * @param string $organizationName
     */
    public function addNewOrganization($organizationName) {
        $org = new Organization();
        $org->setName($organizationName);

        $this->getEntityManager()->persist($org);
        $this->getEntityManager()->flush($org);
    }
}
