<?php

namespace Salt\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserDocAclRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserDocAclRepository extends EntityRepository
{
}
