<?php

namespace CftfBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Salt\UserBundle\Entity\ImportationLog;

/**
 * ImportationLogRepository
 *
 * This class was generated by Vim. Add your own custom
 * repository methods below.
 */
class ImportationLogRepository extends EntityRepository
{
}

