<?php

namespace CftfBundle\Repository;

/**
 * LsDocAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LsDocAttributeRepository extends \Doctrine\ORM\EntityRepository
{
}
