branches:
  only:
    - master
    - develop
    - /^[0-9].*$/

sudo: required

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - DOCKER_COMPOSE_VERSION=1.16.1
    - FIREBASE_PREFIX=${FIREBASE_PREFIX:-travis}-${TRAVIS_BUILD_NUMBER}

language: php

php:
  - '7.1'

cache:
  directories:
    - vendor

services:
  - docker

#apt addons:

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker -v
  - docker-compose -v

# Create the application artifacts
install:
  - ln -s docker-compose.test.yml docker/docker-compose.yml
  - ln -s .env.test docker/.env
  - ln -s docker/.env ./.env
  - echo ${TRAVIS_BUILD_NUMBER} > BUILD_NUMBER
  - echo $(date -u +%Y%m%d.%H%M).${COMMIT} > BUILD_MD
  - echo $(cat VERSION).$(cat BUILD_NUMBER)+$(cat BUILD_MD) > web/version.txt
  - ./bin/build.sh

# Create docker image with the running code
before_script:
  - ./docker/app/build.sh
  - docker-compose -f docker/docker-compose.yml up -d
  - sleep 30

# Run the tests
script:
  - ./bin/console --env=prod doctrine:migrations:migrate -q --no-interaction
  - ./bin/console --env=prod import:generic-csv tests/_data/test_items.csv
  - echo 'Running tests...' && echo -en 'travis_fold:start:run.tests\\r'
  - ./bin/run-tests ${RUN_TEST_ARGS:-"--steps -x duplicate -x skip -x skip-firefox"}
  - echo -en 'travis_fold:end:run.tests\\r'
#  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/build_pull_request; fi'
#  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/build_normal; fi'

#before_cache:

#$TRAVIS_TEST_RESULT has build result 0==success
after_success:
  - ./bin/console --env=prod firebase:clear
  - if [ "$OPENSALT_HEROKU_DEPLOY" != "true" ]; then ./ci/travis/push_app.sh; fi
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then /bin/true; fi

after_failure:
  - echo "Tests FAILED"
  - ./bin/console --env=prod firebase:clear
  - ./ci/travis/send_errors.sh


#before_deploy:

#deploy:
#  skip_cleanup: true

before_deploy:
  - ./deploying/heroku/config_deploy.sh

deploy:
  provider: heroku
  api_key: "${OPENSALT_HEROKU_TOKEN}"
  app: "${OPENSALT_HEROKU_APP}"
  on:
    repo: "${TRAVIS_REPO_SLUG}"
    condition: $OPENSALT_HEROKU_DEPLOY = "true"
    branch: master
  run: "php bin/console-real doctrine:migrations:migrate --no-interaction"

#after_deploy:

after_script:
  - docker-compose -f docker/docker-compose.yml -f docker/docker-compose.tools.yml down -v

notifications:
  hipchat:
    rooms:
      secure: nnj4UI4oXCCT3UYPCcaXONoKmtj6Hf7zM7ysDmWlqBaH0oJiZIbReF3IqBl4EoOkteZ+gBJBVfstmTsTCPkgfCC7rrKj2KkkINS4rskzFUmvG84cJmsFyzdOJv3ArXiWU4YNdZJGggP0lXwxr/fNx8t1VVpdHzt6kHDm3pemoc/yuRiljJI4oPDTkNVIiuD/sRtk0OZt4CFDA3Dnm6fUtwKVBDQ3sEQpu2hCkx1BycISnpkksx+BmYlbmik3jBbdov7dwLOF2HS8YAeDH1Qo6y8Dh8Y94Vtx48w2eX5E0SUdlQj9FPRGh5MrVWxY5/UH1CNNFiTgfkqC+YQ3JR6AFMhSWJWVRnxsGws12GpK3J6WGVRPmAYweTcljJn1HTHi+vjfZbajsqZsEN6XrFXA6I/TPIjfVQO9Gb2HeK/DxMjbYTiReg7Sb4JMJwER63d2yyxmirusnR3JpH86c5z1YSa8I4T3vLKrzPuterj8f99kYHb4Yb8KcVF3aSTxI0ObmKR5AZqWNw0JX6yopUf2Y8barI2/FwpMpkUNaun7U0bECPhq9qdfXWh0BSjpHnXSRXsQH3e4PHDOPLcaK0itf8JT8UdCugo+cTrdIJMv72Jfno5AjG5lduSsWDErBOFj/y7pKDbgHrO1oVfrb5CgeXs9xumEWIW9efjjr5C+fUw=
