<?php

declare(strict_types=1);

namespace App\VectorSearch\Command;

use App\VectorSearch\Service\EmbeddingService;
use App\VectorSearch\Service\VectorSearchService;
use App\VectorSearch\Service\VectorTableService;
use App\VectorSearch\Store\QdrantVectorStore;
use Doctrine\DBAL\Connection;
use Doctrine\DBAL\ParameterType;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

#[AsCommand(
    name: 'vector:qdrant:rebuild-by-framework',
    description: 'Rebuild the Qdrant vector index framework-by-framework into a fresh collection'
)]
class RebuildQdrantIndexByFrameworkCommand extends Command
{
    public function __construct(
        private readonly Connection $connection,
        private readonly EmbeddingService $embeddingService,
        private readonly VectorSearchService $vectorSearchService,
        private readonly VectorTableService $vectorTableService,
        private readonly QdrantVectorStore $qdrantVectorStore,
    ) {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this
            ->addOption('batch-size', 'b', InputOption::VALUE_OPTIONAL, 'Number of embeddings to generate per batch', 250)
            ->addOption('collection', 'c', InputOption::VALUE_OPTIONAL, 'Explicit shadow collection name; defaults to an autogenerated rebuild name')
            ->addOption('activate', 'a', InputOption::VALUE_NONE, 'Atomically activate the rebuilt collection through the configured alias')
            ->addOption('drop-old', null, InputOption::VALUE_NONE, 'Delete the previously active collection after activation')
            ->addOption('recreate', null, InputOption::VALUE_NONE, 'Delete the target shadow collection first if it already exists')
            ->addOption('framework-id', null, InputOption::VALUE_OPTIONAL, 'Process only a single framework by its ls_doc ID')
            ->addOption('after-framework-id', null, InputOption::VALUE_OPTIONAL, 'Resume processing after this framework ID', '0')
            ->setHelp(
                <<<'EOF'
The <info>vector:qdrant:rebuild-by-framework</info> command builds a fresh Qdrant collection
by iterating framework-by-framework instead of by item ID. Each framework's graph is loaded
exactly once, eliminating redundant SQL queries and maximizing the text-building cache.

Examples:
  <info>php bin/console vector:qdrant:rebuild-by-framework</info>
  <info>php bin/console vector:qdrant:rebuild-by-framework --activate</info>
  <info>php bin/console vector:qdrant:rebuild-by-framework --activate --drop-old</info>
  <info>php bin/console vector:qdrant:rebuild-by-framework --framework-id=42</info>
  <info>php bin/console vector:qdrant:rebuild-by-framework --after-framework-id=100</info>
  <info>php bin/console vector:qdrant:rebuild-by-framework --batch-size=500 --activate</info>
EOF
            );
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        ini_set('memory_limit', '1G');

        $io = new SymfonyStyle($input, $output);
        $batchSize = max(1, (int) $input->getOption('batch-size'));
        $activate = (bool) $input->getOption('activate');
        $dropOld = (bool) $input->getOption('drop-old');
        $recreate = (bool) $input->getOption('recreate');
        $frameworkId = $input->getOption('framework-id');
        $afterFrameworkId = max(0, (int) $input->getOption('after-framework-id'));

        if (null !== $frameworkId) {
            $frameworkId = (int) $frameworkId;
        }

        $targetCollection = trim((string) $input->getOption('collection'));
        if ('' === $targetCollection) {
            $targetCollection = $this->qdrantVectorStore->buildShadowCollectionName();
        }

        $alias = $this->qdrantVectorStore->getCollectionAlias();
        $currentActiveCollection = $this->qdrantVectorStore->getResolvedActiveCollectionName();

        $io->title('Qdrant Rebuild By Framework');
        $io->text(sprintf('Target shadow collection: %s', $targetCollection));
        $io->text(sprintf('Current active collection: %s', $currentActiveCollection ?? 'none'));
        $io->text(sprintf('Configured alias: %s', $alias ?? 'not configured'));
        $io->text(sprintf('Batch size: %d', $batchSize));

        if ($activate && null === $alias) {
            $io->error('Cannot use --activate without VECTOR_SEARCH_QDRANT_ALIAS being configured.');

            return Command::FAILURE;
        }

        $this->qdrantVectorStore->createCollection($targetCollection, $recreate);

        $frameworks = $this->fetchAllFrameworks($afterFrameworkId, $frameworkId);
        $io->text(sprintf('Frameworks to process: %d', count($frameworks)));

        $totalImported = 0;
        $frameworkIndex = 0;
        $frameworkCount = count($frameworks);

        foreach ($frameworks as $framework) {
            ++$frameworkIndex;
            $fwId = (int) $framework['id'];
            $fwTitle = (string) $framework['title'];
            $itemCount = $this->countItemsInFramework($fwId);

            $io->section(sprintf(
                '[%d/%d] Framework %d: %s (%d items)',
                $frameworkIndex,
                $frameworkCount,
                $fwId,
                $fwTitle,
                $itemCount
            ));

            if (0 === $itemCount) {
                $io->text('  Skipping empty framework.');
                continue;
            }

            try {
                $rows = $this->vectorSearchService->buildAllEmbeddingRowsForFramework($fwId);
            } catch (\Throwable $e) {
                $io->warning(sprintf(
                    'Failed to build embedding rows for framework %d: %s',
                    $fwId,
                    $e->getMessage()
                ));
                continue;
            }

            if ([] === $rows) {
                $io->text('  No embedding rows produced — skipping.');
                continue;
            }

            $frameworkImported = 0;
            $chunks = array_chunk($rows, $batchSize);

            foreach ($chunks as $chunkIndex => $chunk) {
                $texts = array_map(
                    static fn (array $row): string => $row['text'],
                    $chunk
                );

                $vectors = $this->embeddingService->generateBatchEmbeddings($texts);

                $payloadRows = [];
                foreach ($chunk as $index => $row) {
                    $vector = $vectors[$index] ?? null;
                    if (!is_array($vector)) {
                        throw new \RuntimeException(sprintf(
                            'Missing generated embedding for LsItem %d in framework %d.',
                            $row['lsItemId'],
                            $fwId
                        ));
                    }

                    $payloadRows[] = [
                        ...$row,
                        'vector' => $vector,
                    ];
                }

                $imported = $this->qdrantVectorStore->importEmbeddings($payloadRows, $targetCollection);
                $this->vectorTableService->storeEmbeddingMetadataBatch($payloadRows, true);
                $frameworkImported += $imported;

                $io->text(sprintf(
                    '  Batch %d/%d: %d/%d items imported',
                    $chunkIndex + 1,
                    count($chunks),
                    $frameworkImported,
                    count($rows)
                ));
            }

            $totalImported += $frameworkImported;
            $io->text(sprintf('  Framework %d complete: %d items processed.', $fwId, $frameworkImported));

            // Free memory between frameworks
            unset($rows, $payloadRows, $chunks, $vectors);
            gc_collect_cycles();
        }

        $collectionCount = $this->qdrantVectorStore->countCollection($targetCollection);
        $io->section('Validation');
        $io->listing([
            sprintf('Total frameworks processed: %d', $frameworkCount),
            sprintf('Total items imported: %d', $totalImported),
            sprintf('Target collection count: %d', $collectionCount),
        ]);

        if ($collectionCount !== $totalImported) {
            $io->warning(sprintf(
                'Collection count (%d) does not match imported row count (%d). Review before activation.',
                $collectionCount,
                $totalImported
            ));
        }

        return $this->finishExecution($io, $activate, $dropOld, $alias, $targetCollection);
    }

    /**
     * @return list<array{id: int, identifier: string, title: string}>
     */
    private function fetchAllFrameworks(int $afterFrameworkId = 0, ?int $frameworkId = null): array
    {
        $queryBuilder = $this->connection->createQueryBuilder();
        $queryBuilder
            ->select('d.id', 'd.identifier', 'd.title')
            ->from('ls_doc', 'd')
            ->orderBy('d.id', 'ASC');

        if (null !== $frameworkId) {
            $queryBuilder
                ->where('d.id = :frameworkId')
                ->setParameter('frameworkId', $frameworkId, ParameterType::INTEGER);
        } elseif ($afterFrameworkId > 0) {
            $queryBuilder
                ->where('d.id > :afterFrameworkId')
                ->setParameter('afterFrameworkId', $afterFrameworkId, ParameterType::INTEGER);
        }

        $rows = $queryBuilder->executeQuery()->fetchAllAssociative();

        return array_map(
            static fn (array $row): array => [
                'id' => (int) $row['id'],
                'identifier' => (string) $row['identifier'],
                'title' => (string) ($row['title'] ?? ''),
            ],
            $rows
        );
    }

    private function countItemsInFramework(int $frameworkId): int
    {
        $count = $this->connection->fetchOne(
            'SELECT COUNT(*) FROM ls_item WHERE ls_doc_id = :frameworkId',
            ['frameworkId' => $frameworkId],
            ['frameworkId' => ParameterType::INTEGER]
        );

        return false !== $count ? (int) $count : 0;
    }

    private function finishExecution(
        SymfonyStyle $io,
        bool $activate,
        bool $dropOld,
        ?string $alias,
        string $targetCollection,
    ): int {
        if ($activate) {
            $previousCollection = $this->qdrantVectorStore->activateCollection($targetCollection, $alias);
            $io->success(sprintf(
                'Alias %s now points to %s. Previous collection: %s',
                $alias,
                $targetCollection,
                $previousCollection ?? 'none'
            ));

            if ($dropOld) {
                $deletedCollections = [];
                foreach ($this->qdrantVectorStore->listCollections() as $collectionName) {
                    if ($collectionName === $targetCollection) {
                        continue;
                    }

                    $this->qdrantVectorStore->deleteCollection($collectionName);
                    $deletedCollections[] = $collectionName;
                }

                if ([] !== $deletedCollections) {
                    $io->note(sprintf(
                        'Deleted non-active collections: %s',
                        implode(', ', $deletedCollections)
                    ));
                } else {
                    $io->note('No non-active collections remained to delete.');
                }
            }
        } else {
            $io->success(sprintf('Finished rebuilding shadow collection %s.', $targetCollection));
            if (null !== $alias) {
                $io->note(sprintf(
                    'Run this command again with --activate to atomically point alias %s at %s.',
                    $alias,
                    $targetCollection
                ));
            }
        }

        return Command::SUCCESS;
    }
}
