<?php

declare(strict_types=1);

namespace App\VectorSearch\Command;

use App\VectorSearch\Service\VectorSearchService;
use App\VectorSearch\Store\HybridQdrantStore;
use Doctrine\DBAL\Connection;
use Doctrine\DBAL\ParameterType;
use Symfony\AI\Platform\PlatformInterface;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

#[AsCommand(
    name: 'vector:qdrant:rebuild',
    description: 'Rebuild the Qdrant vector index into a fresh collection and optionally hot-swap it'
)]
class RebuildQdrantIndexCommand extends Command
{
    public function __construct(
        private readonly Connection $connection,
        private readonly PlatformInterface $platform,
        private readonly VectorSearchService $vectorSearchService,
        private readonly HybridQdrantStore $qdrantStore,
    ) {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this
            ->addOption('batch-size', 'b', InputOption::VALUE_OPTIONAL, 'Number of embeddings to generate per batch', 250)
            ->addOption('after-id', null, InputOption::VALUE_OPTIONAL, 'Resume rebuilding after this LsItem ID', 0)
            ->addOption('limit', 'l', InputOption::VALUE_OPTIONAL, 'Optional maximum number of items to rebuild', 0)
            ->addOption('source', 's', InputOption::VALUE_OPTIONAL, 'Rebuild source: auto, qdrant, generate, or items', 'auto')
            ->addOption('collection', 'c', InputOption::VALUE_OPTIONAL, 'Explicit shadow collection name; defaults to an autogenerated rebuild name')
            ->addOption('activate', 'a', InputOption::VALUE_NONE, 'Atomically activate the rebuilt collection through the configured alias')
            ->addOption('drop-old', null, InputOption::VALUE_NONE, 'Delete the previously active collection after activation')
            ->addOption('recreate', null, InputOption::VALUE_NONE, 'Delete the target shadow collection first if it already exists')
            ->setHelp(
                <<<'EOF'
The <info>vector:qdrant:rebuild</info> command builds a fresh Qdrant collection, preferring a fast copy from the
currently active Qdrant collection when possible and otherwise rebuilding from stored vectors, embedding metadata,
or directly from <comment>ls_item</comment> when bootstrapping for the first time. It can then activate the new
collection through the configured alias for a hot-swap style cutover.

Examples:
  <info>php bin/console vector:qdrant:rebuild</info>
  <info>php bin/console vector:qdrant:rebuild --source=qdrant --activate</info>
  <info>php bin/console vector:qdrant:rebuild --source=items --activate</info>
  <info>php bin/console vector:qdrant:rebuild --activate</info>
  <info>php bin/console vector:qdrant:rebuild --batch-size=500 --activate --drop-old</info>
  <info>php bin/console vector:qdrant:rebuild --collection=ls_item_embeddings__rebuild__manual</info>
EOF
            );
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $batchSize = max(1, (int) $input->getOption('batch-size'));
        $afterId = max(0, (int) $input->getOption('after-id'));
        $limit = max(0, (int) $input->getOption('limit'));
        $source = strtolower(trim((string) $input->getOption('source')));
        $activate = (bool) $input->getOption('activate');
        $dropOld = (bool) $input->getOption('drop-old');
        $recreate = (bool) $input->getOption('recreate');

        $requestedCollection = trim((string) $input->getOption('collection'));
        $hasExplicitCollection = '' !== $requestedCollection;
        $targetCollection = $requestedCollection;
        if (!$hasExplicitCollection) {
            $targetCollection = $this->qdrantStore->buildShadowCollectionName();
        }

        $alias = $this->qdrantStore->getCollectionAlias();
        $currentActiveCollection = $this->qdrantStore->getResolvedActiveCollectionName();

        $io->title('Qdrant Rebuild');
        $io->text(sprintf('Target shadow collection: %s', $targetCollection));
        $io->text(sprintf('Current active collection: %s', $currentActiveCollection ?? 'none'));
        $io->text(sprintf('Configured alias: %s', $alias ?? 'not configured'));
        $io->text(sprintf('Selected rebuild source: %s', $source));
        if ($limit > 0) {
            $io->text(sprintf('Rebuild limit set to %d items.', $limit));
        }

        if (!in_array($source, ['auto', 'qdrant', 'generate', 'items'], true)) {
            $io->error('Invalid --source value. Use auto, qdrant, generate, or items.');

            return Command::FAILURE;
        }

        if ($activate && null === $alias) {
            $io->error('Cannot use --activate without VECTOR_SEARCH_QDRANT_ALIAS being configured.');

            return Command::FAILURE;
        }

        if ('qdrant' === $source && null === $currentActiveCollection) {
            $io->error('Cannot rebuild from Qdrant because there is no active source collection.');

            return Command::FAILURE;
        }

        if ('qdrant' === $source && $targetCollection === $currentActiveCollection) {
            $io->error('Target collection must be different from the currently active collection when rebuilding from Qdrant.');

            return Command::FAILURE;
        }

        $effectiveSource = $this->resolveSource($source, $currentActiveCollection, $afterId, $limit);
        $io->text(sprintf('Effective rebuild source: %s', $effectiveSource));

        if ('qdrant' === $effectiveSource && $targetCollection === $currentActiveCollection) {
            $io->error('Target collection must be different from the currently active collection when rebuilding from Qdrant.');

            return Command::FAILURE;
        }

        $collectionCreated = $this->qdrantStore->prepareCollection($targetCollection, $recreate, $hasExplicitCollection);
        $startingCollectionCount = $collectionCreated ? 0 : $this->qdrantStore->countCollection($targetCollection);

        $io->text($collectionCreated
            ? sprintf('Creating target collection: %s', $targetCollection)
            : sprintf('Resuming existing target collection: %s (%d points already present)', $targetCollection, $startingCollectionCount)
        );

        $rebuilt = 0;
        $skippedEmptyText = 0;
        $lastLsItemId = $afterId;

        if ('qdrant' === $effectiveSource) {
            $io->section('Fast Copy');
            $rebuilt = $this->qdrantStore->cloneCollection(
                $currentActiveCollection,
                $targetCollection,
                $batchSize,
                $afterId,
                $limit
            );

            $collectionCount = $this->qdrantStore->countCollection($targetCollection);
            $expectedCollectionCount = $startingCollectionCount + $rebuilt;
            $io->listing([
                sprintf('Copy source: %s', $currentActiveCollection),
                sprintf('Copied rows this run: %d', $rebuilt),
                sprintf('Target collection count: %d', $collectionCount),
            ]);

            if ($collectionCount !== $expectedCollectionCount) {
                $io->warning(sprintf(
                    'Collection count (%d) does not match the expected count after this run (%d). Review before activation.',
                    $collectionCount,
                    $expectedCollectionCount
                ));
            }

            return $this->finishExecution($io, $activate, $dropOld, $alias, $targetCollection);
        }

        if ('items' === $effectiveSource) {
            while (true) {
                $remaining = $limit > 0 ? max(0, $limit - $rebuilt) : null;
                if (null !== $remaining && 0 === $remaining) {
                    break;
                }

                $requestedItems = $this->fetchLsItemBatch($lastLsItemId, min($batchSize, $remaining ?? $batchSize));
                if ([] === $requestedItems) {
                    break;
                }

                foreach ($this->groupRequestedItemsByFramework($requestedItems) as $frameworkId => $frameworkItemIds) {
                    $rows = $this->vectorSearchService->buildEmbeddingRowsForFramework($frameworkId, $frameworkItemIds);
                    ['rows' => $rows, 'skipped' => $batchSkippedEmpty] = $this->partitionEmbeddableRows($rows);
                    $skippedEmptyText += $batchSkippedEmpty;
                    if ([] === $rows) {
                        continue;
                    }

                    $texts = array_column($rows, 'text');
                    $deferredResult = $this->platform->invoke('Xenova/all-MiniLM-L6-v2', $texts);
                    $vectors = array_map(
                        static fn (\Symfony\AI\Platform\Vector\Vector $v): array => $v->getData(),
                        $deferredResult->asVectors()
                    );
                    $payloadRows = [];

                    foreach ($rows as $index => $row) {
                        $vector = $vectors[$index] ?? null;
                        if (!is_array($vector)) {
                            throw new \RuntimeException(sprintf('Missing generated embedding for LsItem %d during ls_item bootstrap.', $row['lsItemId']));
                        }

                        $payloadRows[] = [
                            ...$row,
                            'vector' => $vector,
                        ];
                    }

                    $rebuilt += $this->qdrantStore->importEmbeddings($payloadRows, $targetCollection);
                }

                $lastLsItemId = (int) $requestedItems[array_key_last($requestedItems)]['id'];
                $io->text(sprintf(
                    'Bootstrapped %d embeddings from ls_item so far into %s. Last LsItem ID: %d.',
                    $rebuilt,
                    $targetCollection,
                    $lastLsItemId
                ));
            }

            $collectionCount = $this->qdrantStore->countCollection($targetCollection);
            $expectedCollectionCount = $startingCollectionCount + $rebuilt;
            $io->section('Validation');
            $validationItems = [
                sprintf('Bootstrapped rows this run: %d', $rebuilt),
                sprintf('Items skipped due to empty embedding text: %d', $skippedEmptyText),
                sprintf('Target collection count: %d', $collectionCount),
                sprintf('Last processed LsItem ID: %d', $lastLsItemId),
            ];
            if (!$collectionCreated) {
                $validationItems[] = sprintf('Starting target collection count: %d', $startingCollectionCount);
            }
            $io->listing($validationItems);

            if ($collectionCount !== $expectedCollectionCount) {
                $io->warning(sprintf(
                    'Collection count (%d) does not match the expected count after this run (%d). Review before activation.',
                    $collectionCount,
                    $expectedCollectionCount
                ));
            }

            return $this->finishExecution($io, $activate, $dropOld, $alias, $targetCollection);
        }

        $io->error(sprintf('Unsupported rebuild source: %s', $effectiveSource));

        return Command::FAILURE;
    }

    /**
     * @param list<array{
     *   lsItemId: int,
     *   frameworkId: int,
     *   kind: int,
     *   text: string,
     *   isLeafNode: bool,
     *   sourceHierarchyUpdatedAt: \DateTimeImmutable
     * }> $rows
     * @return array{
     *   rows: list<array{
     *     lsItemId: int,
     *     frameworkId: int,
     *     kind: int,
     *     text: string,
     *     isLeafNode: bool,
     *     sourceHierarchyUpdatedAt: \DateTimeImmutable
     *   }>,
     *   skipped: int
     * }
     */
    private function partitionEmbeddableRows(array $rows): array
    {
        $filteredRows = [];
        $skipped = 0;

        foreach ($rows as $row) {
            if ('' === trim($row['text'])) {
                ++$skipped;
                continue;
            }

            $filteredRows[] = $row;
        }

        return [
            'rows' => $filteredRows,
            'skipped' => $skipped,
        ];
    }

    private function resolveSource(string $source, ?string $currentActiveCollection, int $afterId, int $limit): string
    {
        if ('auto' !== $source) {
            return $source;
        }

        if (null !== $currentActiveCollection && 0 === $afterId && 0 === $limit) {
            return 'qdrant';
        }

        return 'items';
    }

    /**
     * @return list<array{id: int, frameworkId: int}>
     */
    private function fetchLsItemBatch(int $afterId, int $batchSize): array
    {
        $rows = $this->connection->fetchAllAssociative(
            <<<'SQL'
                SELECT id, ls_doc_id AS framework_id
                FROM ls_item
                WHERE id > :afterId
                ORDER BY id ASC
                LIMIT :batchSize
            SQL,
            [
                'afterId' => $afterId,
                'batchSize' => $batchSize,
            ],
            [
                'afterId' => ParameterType::INTEGER,
                'batchSize' => ParameterType::INTEGER,
            ]
        );

        return array_map(
            static fn (array $row): array => [
                'id' => (int) $row['id'],
                'frameworkId' => (int) $row['framework_id'],
            ],
            $rows
        );
    }

    /**
     * @param list<array{id: int, frameworkId: int}> $requestedItems
     * @return array<int, list<int>>
     */
    private function groupRequestedItemsByFramework(array $requestedItems): array
    {
        $grouped = [];
        foreach ($requestedItems as $requestedItem) {
            $grouped[$requestedItem['frameworkId']] ??= [];
            $grouped[$requestedItem['frameworkId']][] = $requestedItem['id'];
        }

        return $grouped;
    }

    private function finishExecution(
        SymfonyStyle $io,
        bool $activate,
        bool $dropOld,
        ?string $alias,
        string $targetCollection,
    ): int {
        $previousCollection = null;
        if ($activate) {
            $previousCollection = $this->qdrantStore->activateCollection($targetCollection, $alias);
            $io->success(sprintf(
                'Alias %s now points to %s. Previous collection: %s',
                $alias,
                $targetCollection,
                $previousCollection ?? 'none'
            ));

            if ($dropOld) {
                $deletedCollections = [];
                foreach ($this->qdrantStore->listCollections() as $collectionName) {
                    if ($collectionName === $targetCollection) {
                        continue;
                    }

                    $this->qdrantStore->deleteCollection($collectionName);
                    $deletedCollections[] = $collectionName;
                }

                if ([] !== $deletedCollections) {
                    $io->note(sprintf(
                        'Deleted non-active collections: %s',
                        implode(', ', $deletedCollections)
                    ));
                } else {
                    $io->note('No non-active collections remained to delete.');
                }
            }
        } else {
            $io->success(sprintf('Finished rebuilding shadow collection %s.', $targetCollection));
            if (null !== $alias) {
                $io->note(sprintf(
                    'Run this command again with --activate to atomically point alias %s at %s.',
                    $alias,
                    $targetCollection
                ));
            }
        }

        return Command::SUCCESS;
    }

}
