<?php

namespace Tests\Unit\App\Entity\Framework;

use App\Entity\Framework\AssociationSubtype;

class AssociationSubtypeTest extends \Codeception\Test\Unit
{
    /**
     * @var \Tests\Support\UnitTester
     */
    protected $tester;

    // tests
    public function testConstructor()
    {
        $associationSubtype = new AssociationSubtype();

        $this->assertInstanceOf(AssociationSubtype::class, $associationSubtype);
        // ID is auto-generated by Doctrine, so we don't test its initial value
    }

    public function testGetId()
    {
        $associationSubtype = new AssociationSubtype();

        // ID is auto-generated by Doctrine, so we just test the method exists
        $this->assertTrue(method_exists($associationSubtype, 'getId'));
    }

    public function testGetName()
    {
        $associationSubtype = new AssociationSubtype();

        // Since there's no setter, we can't test this directly
        // This test documents the expected behavior
        $this->assertInstanceOf(AssociationSubtype::class, $associationSubtype);
    }

    public function testGetParentType()
    {
        $associationSubtype = new AssociationSubtype();

        // Since there's no setter, we can't test this directly
        // This test documents the expected behavior
        $this->assertInstanceOf(AssociationSubtype::class, $associationSubtype);
    }

    public function testGetDirection()
    {
        $associationSubtype = new AssociationSubtype();

        // Since there's no setter, we can't test this directly
        // This test documents the expected behavior
        $this->assertInstanceOf(AssociationSubtype::class, $associationSubtype);
    }

    public function testGetDescription()
    {
        $associationSubtype = new AssociationSubtype();

        // Since there's no setter, we can't test this directly
        // This test documents the expected behavior
        $this->assertInstanceOf(AssociationSubtype::class, $associationSubtype);
    }

    public function testDirectionConstants()
    {
        $this->assertEquals(0, AssociationSubtype::DIR_BOTH);
        $this->assertEquals(1, AssociationSubtype::DIR_FORWARD);
        $this->assertEquals(-1, AssociationSubtype::DIR_INVERSE);
    }

    public function testValidParentTypes()
    {
        $validTypes = [
            'Is Child Of',
            'Exact Match Of',
            'Is Related To',
            'Is Part Of',
            'Replaced By',
            'Precedes',
            'Has Skill Level',
            'Is Peer Of',
            'Exemplar',
            'Is Translation Of'
        ];

        foreach ($validTypes as $type) {
            $this->assertIsString($type);
            $this->assertNotEmpty($type);
        }
    }

    public function testValidDirections()
    {
        $validDirections = [
            AssociationSubtype::DIR_BOTH,
            AssociationSubtype::DIR_FORWARD,
            AssociationSubtype::DIR_INVERSE
        ];

        foreach ($validDirections as $direction) {
            $this->assertIsInt($direction);
            $this->assertContains($direction, [-1, 0, 1]);
        }
    }

    public function testDirectionValues()
    {
        $this->assertIsInt(AssociationSubtype::DIR_BOTH);
        $this->assertIsInt(AssociationSubtype::DIR_FORWARD);
        $this->assertIsInt(AssociationSubtype::DIR_INVERSE);

        $this->assertGreaterThanOrEqual(-1, AssociationSubtype::DIR_INVERSE);
        $this->assertLessThanOrEqual(1, AssociationSubtype::DIR_FORWARD);
    }

    public function testEntityStructure()
    {
        $associationSubtype = new AssociationSubtype();

        // Test that the entity has the expected structure by checking method existence
        $this->assertTrue(method_exists($associationSubtype, 'getId'));
        $this->assertTrue(method_exists($associationSubtype, 'getName'));
        $this->assertTrue(method_exists($associationSubtype, 'getParentType'));
        $this->assertTrue(method_exists($associationSubtype, 'getDirection'));
        $this->assertTrue(method_exists($associationSubtype, 'getDescription'));
    }
}
