parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   'pdo_mysql'
                #url: '%env(resolve:DATABASE_URL)%'
                host:     '%database_host%'
                port:     '%database_port%'
                dbname:   '%database_name%'
                user:     '%database_user%'
                password: '%database_password%'
                options:  '%pdo_options%'
                charset:  utf8mb4
                schema_filter: ~^(?!(cache_items|LearningStandards|std_|map_|grade_level))~
                # To remove ecotone tables from doctrine migration generation
                #schema_filter: ~^(?!(cache_items|LearningStandards|std_|map_|grade_level|ecotone|event_streams$|projections$|_[0-9a-f]{40}$))~
                server_version: 8.4.4
                use_savepoints: true
                profiling_collect_backtrace: '%kernel.debug%'
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
        types:
            json: App\Doctrine\Types\JsonType
            date: App\Doctrine\Types\DateType
            datetime: App\Doctrine\Types\DateTimeType
            datetimetz_immutable: App\Doctrine\Types\DateTimeTzImmutableType
        #mapping_types:
        #    json: string
        #    uuid: char(36)
    orm:
        auto_generate_proxy_classes: true
        #enable_lazy_ghost_objects: true ## Disabled in favour of enable_native_lazy_objects
        # enable_native_lazy_objects: true ## removed: unsupported by current DoctrineBundle
        controller_resolver:
            auto_mapping: false

        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                #metadata_cache_driver: apc
                #query_cache_driver: apc
                report_fields_where_declared: true
                second_level_cache:
                    enabled: false
                    log_enabled: true
                mappings:
                    App:
                        prefix: App\Entity
                        dir: "%kernel.project_dir%/src/Entity"
                        is_bundle: false
                    Domain:
                        prefix: App\Domain
                        dir: "%kernel.project_dir%/src/Domain"
                        is_bundle: false
                    GedmoTree:
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Tree/Entity"
                        #alias: GedmoTree # (optional) it will default to the name set for the mapping
                        is_bundle: false

#when@test:
#    doctrine:
#        dbal:
#            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
