nelmio_api_doc:
    html_config:
        assets_mode: 'bundle' # Other values: 'cdn', 'bundle', 'offline'
        swagger_ui_config:
            filter: false
            default_sections_opened: false
        redocly_config:
            onlyRequiredInSamples: false
            sortRequiredPropsFirst: true
            hideSchemaTitles: true
            jsonSamplesExpandLevel: 1
        stoplight_config:
            basePath: '/api/v1/doc-stoplight'
            hideSchemas: true
            hideExport: true
            router: memory
    use_validation_groups: true
    type_info: true
    models:
        use_jms: false
    documentation:
        info:
            title: OpenSALT
            description: LER Registry Service
            version: 4.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: Token obtained from UI
        security:
            - Bearer: []
    areas: # to filter documented areas
        default:
            path_patterns:
                #- ^/api/v1(?!(/doc|/lor)$)
                - ^/api/v1/documents
                - ^/api/v1/packages

