framework:
    default_locale: '%locale%'
    enabled_locales: ['en']
    translator:
        #default_path: '%kernel.project_dir%/translations'
        paths:
            - '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'
