app.swagger:
    path: /api/v1/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

app.swagger_ui:
    path: /api/v1/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

## or
app.redocly:
    path: /api/v1/doc-redocly
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.redocly }

app.stoplight:
    path: /api/v1/doc-stoplight
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.stoplight }

