<?php

namespace Codeception\Module;

use App\Service\CodeceptionBridge;
use App\Service\User\UserManager;
use Qandidate\Toggle\ContextFactory;
use Qandidate\Toggle\ToggleManager;

class Symfony2Module extends Symfony
{
    public function _getEntityManager()
    {
        /** @var CodeceptionBridge $bridge */
        $bridge = $this->grabService(CodeceptionBridge::class);

        return $bridge->getEntityManager();
    }

    public function grabService($service)
    {
        switch ($service) {
            case UserManager::class:
            case ToggleManager::class:
            case ContextFactory::class:
                /** @var CodeceptionBridge $bridge */
                $bridge = $this->grabService(CodeceptionBridge::class);

                return $bridge->grabService($service);

            default:
        }

        return parent::grabService($service); // TODO: Change the autogenerated stub
    }
}
