<?php

namespace App\Repository\User;

use App\Entity\Framework\LsDoc;
use App\Entity\User\User;
use App\Entity\User\UserDocAcl;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;

/**
 * UserDocAclRepository.
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserDocAclRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, UserDocAcl::class);
    }

    /**
     * Find an ACL by the document and user.
     *
     * @return object|null
     */
    public function findByDocUser(LsDoc $lsDoc, User $user)
    {
        return $this->findOneBy(['lsDoc' => $lsDoc->getId(), 'user' => $user->getId()]);
    }
}
