<?php

namespace App\Repository\User;

use App\Entity\User\UserDocAcl;
use App\Entity\Framework\LsDoc;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use App\Entity\User\User;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * UserDocAclRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserDocAclRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, UserDocAcl::class);
    }

    /**
     * Find an ACL by the document and user
     *
     * @param \App\Entity\Framework\LsDoc $lsDoc
     * @param \App\Entity\User\User $user
     *
     * @return null|object
     */
    public function findByDocUser(LsDoc $lsDoc, User $user)
    {
        return $this->findOneBy(['lsDoc' => $lsDoc->getId(), 'user' => $user->getId()]);
    }
}
